name: "C/C++ CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: mattnotmitt/doxygen-action@1.9.5
      with:
        doxyfile-path: ./Doxyfile
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make docs
      run: make docs
