name: Publish Release
on:
  workflow_run:
    workflows: ["C/C++ CI"]
    types:
      - completed
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
